### ISSUE TITLE
Skill tags are too close to one another

### ISSUE THREAD

**Issue by jrocketfingers** [jrocketfingers/psi-team-hub#3]
![2016-03-10-233831_132x298_scrot](https://cloud.githubusercontent.com/assets/2845244/13687412/60275534-e71b-11e5-8e8b-6d4019b7eef9.png)

**Comment by jrocketfingers** [comment]
Any update on this?

**Comment by simke9445** [comment]
forgot to mention here, fixed already with a different design.
